const timelineElements = [
    {
        id: 1,
        title: "Graduated from Mumbai University",
        location: "Mumbai, India",
        description: "Completed my bachelors degree in Computer Engineering",
        buttonText: "Details",
        date: "May 2015 - May 2019",
        icon: "study",
        color: "black",
        tech: ["JavaScript", "HTML", "CSS", "Java"],
    },
    {
        id: 2,
        title: "Software Engineer at ConnectWise",
        location: "Tampa, Florida",
        description: "Worked on web development projects",
        buttonText: "Details",
        date: "July 2019 - July 2021",
        icon: "work",
        color: "black",
        tech: ["JavaScript", "HTML", "CSS", "Java"],
    },
    {
        id: 3,
        title: "Senior Software Engineer at ConnectWise",
        location: "Tampa, Florida",
        description: "Worked on web development projects",
        buttonText: "Details",
        date: "July 2021 - July 2022",
        icon: "work",
        color: "black",
        tech: ["JavaScript", "React", "Node.js", "SQL"],
    },
    {
        id: 4,
        title: "Digital Technology Intern at Star Union Dai-ichi Life Insurance Company",
        location: "Mumbai, India",
        description: `• Enhanced YouMatter Android app's Home Screen using Java, Kotlin and XML in Android Studio, resulting in a 25 percent
        boost in user engagement and improved navigation efficiency`,
        buttonText: "Details",
        date: "June 2023 - July 2023",
        icon: "work",
        color: "grey",
        tech: ["React", "HTML", "CSS", "JavaScript", "Angular"],
    },
    {
        id: 5,
        title: "Graduate Peer Leader at Stevens Insitute of Technology",
        location: "Hoboken, New Jersey",
        description: "Transitioned to back-end development role",
        buttonText: "Details",
        date: "August 2023 - Dec 2023",
        icon: "work",
        color: "grey",
        tech: ["Node.js", "JavaScript", "SQL", "Python"],
    },
    {
        id: 6,
        title: "Graduated from Stevens Insitute of Technology",
        location: "Hoboken, New Jersey",
        description: "Completed my masters degree in Computer Science",
        buttonText: "Details",
        date: "August 2022 - Dec 2023",
        icon: "study",
        color: "grey",
        tech: ["JavaScript", "React", "HTML", "CSS", "Python"],
    },
];

export default timelineElements.reverse();